version: '3.9'

services:

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: Europe/Vilnius
    volumes:
      - ./:/var/www/symfony/

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/symfony/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  mysql-data: null
